# /docker-compose.yml
version: '3.8'

services:
  # 1. The Python Extraction API
  ai-backend:
    build: ./backend
    container_name: career-studio-backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    

  # 2. The Next.js Frontend
  web-frontend:
    build: .
    container_name: career-studio-web
    ports:
      - "3000:3000"
    environment:
      # This explicitly tells Next.js how to talk to the Python container!
      - PARSER_URL=http://ai-backend:8000
      - NEXT_PUBLIC_PARSER_URL=http://127.0.0.1:8000
    depends_on:
      - ai-backend